### ISSUE TITLE
Support the Go 1.13 way of wrapping errors

### ISSUE THREAD

**Issue by morningvera** [rotisserie/eris#10]
Even though the Wrap/f methods are preferred, we should also allow users to do something like this: Errorf("some context: %w", err)

**Comment by AlekSi** [comment]
So is this still not supported?

**Comment by morningvera** [comment]
Correct, it's not supported. Do you have a specific need for it?

**Comment by dgunay** [comment]
I work in a codebase where we would like to migrate to eris, but we have hundreds of `fmt.Errorf` calls with the `%w` formatter. This would be a big help. 

Is this a big lift to do? I'd be willing to attempt it if it has a reasonable chance of success.
