### ISSUE TITLE
Add support for error trace filtering

### ISSUE THREAD

**Issue by sum2000** [rotisserie/eris#26]
**Is your feature request related to a problem? Please describe.**
Since the UnWrappedError object stores the complete trace information, it will be cool to have some filtering operations on error traces. This can be a really useful debugging tool

**Describe the solution you'd like**
Multiple ways to do it. We can allow string matching filters or lambda functions. 

**Additional context**
Exploring some potential use cases might help coming up with a better API

**Comment by morningvera** [comment]
@sum2000 I think this is a good idea but probably doesn't fit into the eris package. Seems more appropriate for some kind of error monitoring package like Sentry (which may already support this). Feel free to reopen if you disagree.
