### ISSUE TITLE
Provide getters for StackTrace File, Line and Method

### ISSUE THREAD

**Issue by sum2000** [rotisserie/eris#29]
**Is your feature request related to a problem? Please describe.**
Currently, file, line, and method names are inconvenient to access UnpackedError object. It will be useful to have getters for some of these.

**Describe the solution you'd like**
API can be 
- getFile()
- getLine()
- getRootError()
- getErrorChain()

**Comment by morningvera** [comment]
@sum2000 I don't think getters are any more convenient than simply using dot operators. Let's discuss more if you disagree though.
