### ISSUE TITLE
Invalid mod path

### ISSUE THREAD

**Issue by pierrec** [rotisserie/eris#35]
**Describe the bug**
The go.mod file contains the path "github.com/morningvera/eris" instead of "github.com/rotisserie/eris".

**To Reproduce**
go get github.com/rotisserie/eris

**Expected behavior**
The module is installed.

**Comment by morningvera** [comment]
This should be fixed now if you want to try importing it again. Sorry about that!

**Comment by pierrec** [comment]
It works now. Thanks.
