### ISSUE TITLE
Discord link unusable

### ISSUE THREAD

**Issue by dobegor** [rotisserie/eris#62]
This isn't a bug report.
Discord link isn't usable because there are no channels (that one can view after joining).

<img width="543" alt="image" src="https://user-images.githubusercontent.com/14029650/72614572-48798a80-393b-11ea-8857-9de85a5a5ec3.png">

**Comment by sum2000** [comment]
Which discord link did you try? Then one on the main readme? That seems to be working for me. Try using this invite link https://discord.gg/jNPDvH

**Comment by dobegor** [comment]
The one in the README (https://discordapp.com/channels/659952923073183749/659952923073183756) <-- that's not an invite link, it's just a server + channel ID, and it works because you're already a member. Thanks for the proper link, just joined id.

**Comment by morningvera** [comment]
This should be fixed now, thanks for catching it!
