### ISSUE TITLE
Extend external error with stacktrace but keep the context information that error might have

### ISSUE THREAD

**Issue by philippseith** [rotisserie/eris#82]
When eris.Wrap is used on an external error to add a stacktrace, only its error message is preserved. The external error might already contain context information which is lost.

Possible solution:
Add a field of type error to eris.rootError and return its value on Unwrap

Alternative:
Expose funcs for creating a stacktrace to add an eris.Stack to the external error type (only applicable for owned types)

**Comment by morningvera** [comment]
Thanks for submitting this @philippseith! Your solution could potentially work, and I'm planning to try it out soon. It seems like this could solve more than one problem (see #81).

**Comment by morningvera** [comment]
hey @philippseith, we modified the way we wrap external errors to support this. let me know if you're still having issues with it when you have a chance to try it. and thanks for the feedback!
