### ISSUE TITLE
Missing error chain trace in Sentry

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [rotisserie/eris#83]
When logging to Sentry, error chain trace is missing. Text representation of wrapped errors is there, but no `File:Location` trace.
Using provided example:
```
go run examples/sentry/example.go -dsn=<Valid Sentry DSN>
```
Results in Sentry FULL mode:
```
EXCEPTION(most recent call first)

*eris.rootError
test
*eris.wrapError
wrap 1: test
*eris.wrapError
wrap 2: wrap 1: test
*eris.wrapError
wrap 3: wrap 2: wrap 1: test

example.go in main at line 54
	})
	if initErr != nil {
		log.Fatalf("failed to initialize Sentry: %v", initErr)
	}
	sentry.CaptureException(err)
	sentry.Flush(time.Second * 5)
}
```
Results in Sentry RAW mode:
```
EXCEPTION(most recent call first)

*eris.wrapError: wrap 3: wrap 2: wrap 1: test
  File "example.go", line 54, in main
    sentry.CaptureException(err)
```

**Comment by sum2000** [comment]
Thanks @Dragomir-Ivanov , looking into it.

**Comment by sum2000** [comment]
Hey @Dragomir-Ivanov, this issue has been fixed. Let us know if you are still unable to see the trace on Sentry. Thanks for the input.

**Comment by Dragomir-Ivanov** [comment]
Great @sum2000 , will test this soon. Thanks a lot!
